### PR TITLE
Remove  "type": "module" to make common js available

### PR DESCRIPTION
**Pull request by simonboisset**
this fix this issue: #1

### CODE REVIEW

**Comment by goenning** [comment]
Im pretty sure I had to add this to make it compatible with Next.js, so I need to verify it doesn't break it first.

By the way, just an FYI that this package only works on the client side. I have plans for a nextjs specific package which will work on both client/server, and it might be a good timing to do one for remix too.

**Comment by simonboisset** [comment]
You're right, I hadn't considered Next.js compatibility.
Your idea of a Next.js specific package for client/server sounds interesting. Let me know if you need any help for that.

**Comment by goenning** [comment]
Yeah, I'd definitely accept some help :)

My plan was to change this repo to be a monorepo and host all js-related packages like `@aptabase/web`, `@aptabase/next` and `@aptabase/remix`

The implementation is quite simple and there's probably a lot to share between them, most of the work would be on setting up the monorepo with different packages, examples, etc. Would you like to give it a try? We could start with `web` and `remix` as well

**Comment by simonboisset** [comment]
Yes sure, monorepo is really nice for js packages. I can suggest you turborepo. It works great for me. 
It's not perfect but you can take a look to my repo [here](https://github.com/simonboisset/validest) to see an exemple that I use to publish multiple packages.
I would also be happy to help to set up this type of configuration. I remain available if you wish

**Comment by goenning** [comment]
I love that setup, would you like to PR a similar setup it to this repo?

**Comment by simonboisset** [comment]
Of course i can do it in the next few days

**Comment by simonboisset** [comment]
Hi! 
Sorry for the delay but I was really busy this month.

I created a PR => #3 
You can take a look

**Comment by goenning** [comment]
Closing this, let's continue on #1

**Pull request closed without merging**
